"""Generate JSON-only bridge declarations directly from Python annotations."""

import inspect
import json
import sys
import types
from pathlib import Path
from typing import Literal, Union, get_args, get_origin, get_type_hints, is_typeddict

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from api.api import PyWebViewApi  # noqa: E402
from schemas.app_state import BridgeState  # noqa: E402


def generate() -> str:
    """Fail on unsupported annotations rather than silently weakening types to any."""
    definitions: dict[str, str] = {}

    def render(annotation: object) -> str:
        """Map the JSON types used by this project's public contract."""
        primitives = {
            str: "string",
            int: "number",
            float: "number",
            bool: "boolean",
            type(None): "null",
        }
        if annotation in primitives:
            return primitives[annotation]
        origin, args = get_origin(annotation), get_args(annotation)
        if is_typeddict(annotation):
            name = annotation.__name__
            if name not in definitions:
                definitions[name] = ""
                fields = [
                    f"  {key}: {render(value)};"
                    for key, value in get_type_hints(annotation).items()
                ]
                definitions[name] = (
                    f"export type {name} = {{\n" + "\n".join(fields) + "\n};"
                )
            return name
        if origin is list:
            return f"Array<{render(args[0])}>"
        if origin in (Union, types.UnionType):
            return " | ".join(render(arg) for arg in args)
        if origin is Literal:
            return " | ".join(json.dumps(arg) for arg in args)
        raise TypeError(f"Unsupported bridge annotation: {annotation!r}")

    methods = []
    for name, method in inspect.getmembers(PyWebViewApi, inspect.isfunction):
        if name.startswith("_"):
            continue
        hints = get_type_hints(method)
        parameters = []
        for parameter in inspect.signature(method).parameters.values():
            if parameter.name == "self":
                continue
            optional = "?" if parameter.default is not inspect.Parameter.empty else ""
            parameters.append(
                f"{parameter.name}{optional}: {render(hints[parameter.name])}"
            )
        result = "void" if hints["return"] is type(None) else render(hints["return"])
        methods.append(f"  {name}({', '.join(parameters)}): Promise<{result}>;")
    render(BridgeState)
    header = (
        "// Generated by pnpm gen-api. Edit Python annotations, then regenerate.\n\n"
    )
    api = "export interface PyWebViewApi {\n" + "\n".join(methods) + "\n}\n"
    return (
        header
        + "\n\n".join(definitions.values())
        + "\n\n"
        + api
        + "\nexport type PyWebViewApiType = PyWebViewApi;\n"
    )


if __name__ == "__main__":
    target = ROOT / "frontend/src/types/pywebview/pywebview-api.d.ts"
    output = generate()
    if "--check" in sys.argv:
        if target.read_text(encoding="utf-8") != output:
            raise SystemExit("Bridge declarations are stale. Run pnpm gen-api.")
    else:
        target.write_text(output, encoding="utf-8")
