// Generated by pnpm gen-api. Edit Python annotations, then regenerate.

export type Job = {
  id: string;
  kind: "transcription" | "download";
  status: "idle" | "loading" | "running" | "cancelling" | "completed" | "cancelled" | "error";
  progress: number | null;
  message: string;
  error: string | null;
  modelId: string;
  startedAt: string;
};

export type AppState = {
  revision: number;
  engine: EngineInfo;
  models: Array<ModelInfo>;
  modelsDirectory: string;
  preferences: Preferences;
  transcriptionFile: FileMetadata | null;
  job: Job;
  notice: string | null;
  transcriptId: string | null;
};

export type EngineInfo = {
  id: string;
  name: string;
  modelFormat: string;
  languages: Array<Language>;
};

export type Language = {
  code: string;
  name: string;
};

export type ModelInfo = {
  id: string;
  name: string;
  description: string;
  sizeLabel: string;
  sourceUrl: string;
  path: string | null;
  isAvailable: boolean;
  isRecommended: boolean;
};

export type Preferences = {
  modelId: string;
  language: string;
  localModelPaths: Array<string>;
  theme: "system" | "light" | "dark";
  interfaceLanguage: "system" | "en" | "es-ES";
};

export type FileMetadata = {
  name: string;
  size: number;
  type: string;
  absolutePath: string;
};

export type Transcript = {
  id: string;
  createdAt: string;
  file: FileMetadata;
  engineId: string;
  modelId: string;
  language: string;
  duration: number;
  segments: Array<TranscriptionSegment>;
};

export type TranscriptionSegment = {
  id: number;
  text: string;
  start: number;
  end: number;
};

export type BridgeState = {
  studio: AppState;
};

export interface PyWebViewApi {
  bind_dropzone(): Promise<boolean>;
  cancel_job(job_id: string): Promise<void>;
  clear_file(): Promise<void>;
  download_model(model_id: string): Promise<Job>;
  export_transcript(job_id: string, format: "txt" | "srt" | "vtt"): Promise<string | null>;
  get_state(): Promise<AppState>;
  get_transcript(job_id: string): Promise<Transcript>;
  open_file_dialog(): Promise<FileMetadata | null>;
  open_models_folder(): Promise<void>;
  refresh_models(): Promise<void>;
  run_transcription(file_path: string, model_name: string, language?: string): Promise<Job>;
  select_model_folder(): Promise<ModelInfo | null>;
  set_appearance(theme: "system" | "light" | "dark", language: "system" | "en" | "es-ES"): Promise<void>;
  set_preferences(model_id: string, language: string): Promise<void>;
}

export type PyWebViewApiType = PyWebViewApi;
